### ISSUE TITLE
SQL: Decouple Owner/Tenant from Address in the Address Table

### ISSUE THREAD

**Issue by fredlawl** [codeforkansascity/tagging_tracker_backend#37]
The address table should not be responsible for owner/tenant information. New table(s) should be created such that and address may exist without an owner or tenant. In addition to that, a owner/tennant should not exist without an address. 

Since the main goal of the application is to track address locations, then there may be cases where an address should be pinned when even though the owner/tenant may not be known at the present time. This information could be added/modified later.

**Comment by kolkheang** [comment]
+1

**Comment by Amertz08** [comment]
IMO we should create 2 models to do this. `Contact` and `ContactType` because a property is likely to have more than just the `Owner/Tenant` dichotomy.

Contact:
- first_name (char)
- last_name (char)
- email (EmailField)
- phone_number (char)
- type (ContactType)
- follow_up (bool)
- notes (text)

ContactType:
- type (char)
