### ISSUE TITLE
Create docker-free workflow.

### ISSUE THREAD

**Issue by Nerdenator** [codeforkansascity/tagging_tracker_backend#52]
Some volunteers can't work on a Docker project. Creation of a non-dockerized version of the project that can be worked on in parallel.

**Comment by kolkheang** [comment]
@Nerdenator - Can you give me some reasons why you don't like Docker?

The reason that the developer isn't able to setup Docker on his device is because his device doesn't meet the requirement for Docker, which requires hardware virtualization.

There is an option to get his computer setup to run the project.  We can ask him to setup the python/django environment on his machine then he can develop the project that way without needing Docker.

**Comment by Amertz08** [comment]
Not going to do as using Docker is the easiest way to install and work with Postgres
